spring:
  application:
    name: vitrify
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:vitrifydb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
logging:
  level:
    ROOT: INFO
    #org.springframework.security: DEBUG
    #org.springframework.security.web.FilterChainProxy: DEBUG
    #org.springframework.web: INFO
    #org.hibernate.orm.jdbc.bind: TRACE
    dev.thiagooliveira: DEBUG
    #liquibase: DEBUG